/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Jan 23 20:42:22 2025 */

/* parameterized module instance */
display_clock __ (.CLKI( ), .CLKOP( ));
