/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Thu Jan 23 20:34:28 2025 */

/* parameterized module instance */
display_buffer __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
