/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Fri Jan 24 14:36:51 2025 */

/* parameterized module instance */
imx_interface __ (.alignwd( ), .clkin( ), .ready( ), .sclk( ), .start( ), 
    .sync_clk( ), .sync_reset( ), .datain( ), .q( ));
